export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as PopularProducts } from "./PopularProducts";
export { default as SuperQuality } from "./SuperQuality";
export { default as CustomerReviews } from "./CustomerReviews";
export { default as RolexBox } from "./RolexBox";
export { default as Services } from "./Services";
export { default as Video } from "./Video";
export { default as Subscribe } from "./Subscribe";
